// 조바(단품 · 테마 옵션 빌더) 다크 — 시트 안 밝은 면 · 버튼 · 푸터 계좌
import { createRequire } from 'node:module'; import fs from 'node:fs'; import path from 'node:path';
const require = createRequire(import.meta.url); const { chromium } = require('playwright');
const S='https://duck-hoo.com', UA='Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1';
const ROOT='/home/user/new-website-build'; const OUT=process.env.OUT||'../dark-probe2'; fs.mkdirSync(OUT,{recursive:true});
const url=process.argv[2]||'/product/%ec%a1%b0%eb%b0%94-%ec%9e%85%ed%98%b8%ed%9d%a1-%ec%a0%84%ec%9e%90%eb%8b%b4%eb%b0%b0/';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-sandbox']});
const ctx=await b.newContext({viewport:{width:390,height:844},userAgent:UA,deviceScaleFactor:2}); const page=await ctx.newPage();
await page.addInitScript(()=>{ try{ localStorage.setItem('dhr-theme','dark'); }catch(e){} });
await page.route('**/*', async route=>{ const u=route.request().url(); if(!/^https?:/.test(u)) return route.abort();
  const lm=process.env.LOCAL==='1' && u.match(/\/plugins\/new-website-build\/assets\/([a-z-]+\.(?:css|js))/); if(lm){ return route.fulfill({status:200,headers:{'content-type':lm[1].endsWith('.css')?'text/css':'application/javascript'},body:fs.readFileSync(path.join(ROOT,'assets',lm[1]))}); }
  try{ const r=await fetch(u,{headers:{'user-agent':UA},redirect:'manual'}); const h={}; r.headers.forEach((v,k)=>{ if(!/^(content-encoding|transfer-encoding|content-length|set-cookie)$/i.test(k)) h[k]=v; }); route.fulfill({status:r.status,headers:h,body:Buffer.from(await r.arrayBuffer())}); }catch(e){ route.abort(); } });
const r=await page.goto(S+url+'?nocache='+Date.now(),{waitUntil:'load',timeout:90000}); console.log('status',r.status());
await page.evaluate(()=>{ document.querySelectorAll('#pop-dim,#pop6,#dh-agegate2').forEach(e=>e.remove()); document.documentElement.classList.remove('dh-ag2-lock'); document.body.classList.remove('dh-ag2-lock'); });
await page.waitForTimeout(2500);
const info=(e)=>{ const c=getComputedStyle(e); return {sel:e.tagName.toLowerCase()+(typeof e.className==='string'&&e.className?'.'+e.className.trim().split(/\s+/).slice(0,4).join('.'):''), bg:c.backgroundColor, color:c.color, op:c.opacity, filter:c.filter, text:(e.innerText||'').trim().slice(0,30), dis:e.disabled}; };
await page.evaluate(()=>window.DHR.openBuySheet()); await page.waitForTimeout(600);
await page.screenshot({path:`${OUT}/sheet.png`});
const light=await page.evaluate(()=>{ const card=document.querySelector('[data-dock]'); const out=[]; card.querySelectorAll('*').forEach(e=>{ const c=getComputedStyle(e); const m=c.backgroundColor.match(/[\d.]+/g); if(!m) return; const [r,g,b,a]=m.map(Number); if(a===0) return; const L=(0.2126*r+0.7152*g+0.0722*b)/255; const r2=e.getBoundingClientRect(); if(L>0.6 && r2.width>20&&r2.height>10) out.push({sel:e.tagName.toLowerCase()+(typeof e.className==='string'&&e.className?'.'+e.className.trim().split(/\s+/).slice(0,4).join('.'):''), bg:c.backgroundColor, color:c.color, w:Math.round(r2.width), h:Math.round(r2.height), text:(e.innerText||'').trim().slice(0,24)}); }); return out; });
console.log('LIGHT', JSON.stringify(light,null,1));
const btns=await page.evaluate(()=>{ return [...document.querySelectorAll('[data-dock] .vf-drawer-actions button, [data-dock] .wd-option-qty *, [data-dock] .wd-qty *, [data-dock] input[type=number], [data-dock] .quantity *, [data-dock] .wd-option-builder-total, [data-dock] .wd-total-price')].map(e=>{ const c=getComputedStyle(e); return {sel:e.tagName.toLowerCase()+(typeof e.className==='string'&&e.className?'.'+e.className.trim().split(/\s+/).slice(0,4).join('.'):''), bg:c.backgroundColor, color:c.color, op:c.opacity, filter:c.filter, text:(e.innerText||e.value||'').trim().slice(0,30), dis:e.disabled, cls:e.className}; }); });
console.log('BTNS', JSON.stringify(btns,null,1));
const html=await page.evaluate(()=>{ const q=document.querySelector('[data-dock] .vf-drawer-actions'); const qty=[...document.querySelectorAll('[data-dock] *')].find(e=>/^수량/.test((e.innerText||'').trim()) && e.children.length<6); return {actions:q?q.outerHTML.slice(0,900):null, qty:qty?qty.outerHTML.slice(0,900):null, qtyParentCls: qty?qty.parentElement.className:null}; });
console.log('HTML', JSON.stringify(html,null,1));
await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight)); await page.waitForTimeout(500);
const fb=await page.evaluate(()=>{ const q=s=>document.querySelector(s); const cs=e=>e&&getComputedStyle(e); const pick=s=>{ const e=q(s); if(!e) return null; const c=cs(e); return {color:c.color,bg:c.backgroundColor,op:c.opacity,text:(e.innerText||'').trim().slice(0,30)}; }; return {fbank:pick('.fbank'), n:pick('.fbank .n'), meta:pick('.fbank__meta'), copy:pick('.fbank__copy'), note:pick('.fbank__note, .fbank p'), title:pick('.fbank h3, .fbank strong, .fbank .fbank__t')}; });
console.log('FBANK', JSON.stringify(fb,null,1));
await page.evaluate(()=>{ const c=document.querySelector('[data-dock]'); if(c.classList.contains('is-sheet')) document.querySelector('[data-dock] [data-dock-close]').click(); });
await page.waitForTimeout(300); await page.evaluate(()=>document.querySelector('.fbank').scrollIntoView()); await page.waitForTimeout(400);
await page.screenshot({path:`${OUT}/fbank.png`});
await b.close();
